controller_frequency:       10    #The rate in Hz at which to run the control loop and send velocity commands to the base
planner_patience:           7.0   #How long the planner will wait in seconds in an attempt to find a valid plan before space-clearing operations are performed.
controller_patience:        8.0  #How long the controller will wait in seconds without receiving a valid control before space-clearing operations are performed.
conservative_reset_dist:    10.0   #The distance away from the robot in meters at which obstacles will be cleared from the costmap when attempting to clear space in the map. Note, this parameter is only used when the default recovery behaviors are used for move_base.
recovery_behavior_enabled:  true  #Whether or not to enable the move_base recovery behaviors to attempt to clear out space.
clearing_rotation_allowed:  false  #Determines whether or not the robot will attempt an in-place rotation when attempting to clear out space. Note: This parameter is only used when the default recovery behaviors are in use, meaning the user has not set the recovery_behaviors parameter to anything custom.
shutdown_costmaps:          false #Determines whether or not to shutdown the costmaps of the node when move_base is in an inactive state
oscillation_timeout:        0.0   #How long in seconds to allow for oscillation before executing recovery behaviors. 0 disable
oscillation_distance:       0.15  #How far in meters the robot must move to be considered not to be oscillating
planner_frequency:          2.0   #The rate in Hz at which to run the global planning loop. 0 => Global plan updates on new goal or path blocked only
max_planning_retries:       10

mbf_tolerance_check: false
dist_tolerance: 0.2
angle_tolerance: 1.5

default_planner: navfn
default_controller: dwa_local_planner

controller:
  holonomic_robot: false
