local_costmap:
  global_frame:           map
  update_frequency:       0.5   # 10.0  
  publish_frequency:      0.5   # 2.0 
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}

  # The following parameters are only used if map_type is set to "costmap":
  obstacle_layer:
    track_unknown_space:    false
    footprint_clearing_enabled: true
  
 ### Map management parameters ### 
  static_map:             false  
  rolling_window:         true
  unknown_cost_value:     0
  publish_voxel_map:      true
  lethal_cost_threshold:  100
  map_topic:              map

    # The following parameters are overwritten if "static_map" is set to true:
  width:                  12.0
  height:                 12.0
  resolution:             0.1
  origin_x:               -6.0
  origin_y:               -6.0

    ### Map type parameters ###
  map_type:               costmap
    #map_type:                voxel


  
  # The following parameters are only used if map_type is set to "voxel":
  #origin_z:              0.2
  #z_resolution:          0.2
  #z_voxels:              2
  #unknown_threshold:     10
  #mark_threshold:        3

  
  
  
  
