global_costmap:
  global_frame:           map
  update_frequency:       0.5
  publish_frequency:      0.5
  plugins: 
    - {name: static_layer, type: 'costmap_2d::StaticLayer'}
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

  # The following parameters are only used if map_type is set to "costmap"
  obstacle_layer:
    track_unknown_space:    false
    footprint_clearing_enabled: true


  ### Robot description parameters ##
  inflation_layer:
    inflation_radius:       2.3
    cost_scaling_factor:    1.0

  static_layer:
    map_topic: 'static_map'
    unknown_cost_value:     0
    publish_voxel_map:      false
    lethal_cost_threshold:  100




  ### Map management parameters ### 
  static_map:             false
  rolling_window:         true


  # The following parameters are overwritten if "static_map" is set to true:

  width:                 100 #15
  height:                100 #15
  resolution:            0.1
  origin_x:              -50.0
  origin_y:              -50.0
  
  ### Map type parameters ###
  map_type:               costmap

  footprint: [[2.2, -0.5], [-0.2, -0.5], [-0.2, 0.5], [2.2, 0.5]]




  # The following parameters are only used if map_type is set to "voxel":
  #origin_z:              0.0
  #z_resolution:          0.2
  #z_voxels:              0.4
  #unknown_threshold:     10
  #mark_threshold:        0

