# http://wiki.ros.org/dwa_local_planner#DWAPlannerROS
DWAPlannerROS:

 # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.

  max_trans_vel:                  0.5
  min_trans_vel:                  0.1
  max_vel_x:                      1.5
  min_vel_x:                      -0.5 #0.0
  max_vel_y:                      0.0
  min_vel_y:                      0.0
  max_rot_vel:                    0.5
  min_rot_vel:                    0.1
  acc_lim_x:                      2.5
  acc_lim_y:                      0.0
  acc_lim_theta:                  2.0 #3.2
  acc_limit_trans:                0.3
  prune_plan:                     false

  xy_goal_tolerance:              0.2
  yaw_goal_tolerance:             0.1
  trans_stopped_vel:              0.1
  rot_stopped_vel:                0.1

  sim_time:                       1.5
  sim_granularity:                0.025
  angular_sim_granularity:        0.1

  path_distance_bias:             50.0 #32.0
  goal_distance_bias:             70.0 #24.0
  occdist_scale:                  0.1

  stop_time_buffer:               0.3
  oscillation_reset_dist:         0.05
  oscillation_reset_angle:        0.2
  forward_point_distance:         0.325
  scaling_speed:                  0.25
  max_scaling_factor:             0.2

  vx_samples:                     20
  vy_samples:                     1 #since there is no vy, there is only one sample vy=0
  vth_samples:                    30
  use_dwa:                        true
  meter_scoring:                  false


# Debugging
  publish_traj_pc:                true
  publish_cost_grid_pc:           true
  global_frame_id:                /odom

  holonomic_robot:                false
  restore_defaults:               false

  latch_xy_goal_tolerance:      false #false
  penalize_negative_x:          true



