GlobalPlanner:
  allow_unknown: true #(bool, default: true)

  visualize_potential: true #(bool, default: false)
  use_dijkstra: true #(bool, default: true)
  use_quadratic: true #(bool, default: true)
  use_grid_path: false #(bool, default: false)
  old_navfn_behavior: false #(bool, default: false)
  publish_plan_poses: true
  publish_scale: 100
  planner_costmap_publish_frequency: 0.0

  default_tolerance: 0.0 #(double, default: 0.0)
  planner_window_x: 0
  planner_window_y: 0

  oriental_filter_mode: 2 #there are 4 options:
                          #0 - NONE
                          #1 - FORWARD
                          #2 - INTERPOLATE
                          #3 - FORWARDTHENINTERPOLATE

