# http://www.ros.org/wiki/navfn
NavfnROS:
  allow_unknown:                      true
  planner_window_x:                   0.0
  planner_window_y:                   0.0
  default_tolerance:                  0.01
  visualize_potential:                true
  #planner_costmap_publish_frequency:  0.5


