PoseFollower:
  k_trans: 2.0
  k_rot: 2.0

  #within this distance to the goal, finally rotate to the goal heading (also, we've reached our goal only if we're within this dist)
  tolerance_trans: 0.2 #0.02

  #we've reached our goal only if we're within this angular distance
  tolerance_rot: 0.1 #0.04

  #we've reached our goal only if we're within range for this long and stopped
  tolerance_timeout: 0.1

  #set this to true if you're using a holonomic robot
  holonomic: false #true

  #number of samples (scaling factors of our current desired twist) to check the validity of
  samples: 10

  #go no faster than this
  max_vel_lin: 2.0 #0.9
  max_vel_th: 2.0 #1.4

  #minimum velocities to keep from getting stuck
  min_vel_lin: 0.1
  min_vel_th: 0.0

  #if we're rotating in place, go at least this fast to avoid getting stuck
  min_in_place_vel_th: 0.0

  #when we're near the end and would be trying to go no faster than this translationally, just rotate in place instead
  in_place_trans_vel: 0.0

  #we're "stopped" if we're going slower than these velocities
  trans_stopped_velocity: 1e-4
  rot_stopped_velocity: 1e-4

  #if this is true, we don't care whether we go backwards or forwards
  allow_backwards: true #false

  #if this is true, turn in place to face the new goal instead of arcing toward it
  turn_in_place_first: true

  #if turn_in_place_first is true, turn in place if our heading is more than this far from facing the goal location
  max_heading_diff_before_moving: 0.17

